name: tch_common_widgets
description: Flutter common widgets & theming package used by tomaschyly.
version: 0.27.2
homepage: https://tomas-chyly.com/en/project/tomas-chyly-common-widgets
repository: https://github.com/tomaschyly/tch_common_widgets
issue_tracker: https://github.com/tomaschyly/tch_common_widgets/issues

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  tch_appliable_core: ^0.25.0

  flutter_svg: ^2.0.7
  intl: ^0.18.1
  jiffy: ^6.2.1

# dependency_overrides:
#   intl: ^0.18.0

flutter:
  plugin:
    platforms:
      android:
        package: com.tomaschyly.tch_common_widgets
        pluginClass: TchCommonWidgetsPlugin
      ios:
        pluginClass: TchCommonWidgetsPlugin
      linux:
        pluginClass: TchCommonWidgetsPlugin
      macos:
        pluginClass: TchCommonWidgetsPlugin
      windows:
        pluginClass: TchCommonWidgetsPlugin
      web:
        pluginClass: TchCommonWidgetsWeb
        fileName: tch_common_widgets_web.dart
