name: tch_common_widgets
description: Flutter common widgets & theming package used by tomaschyly.
version: 0.0.2
# homepage: 
repository: https://github.com/tomaschyly/tch_common_widgets
issue_tracker: https://github.com/tomaschyly/tch_common_widgets/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  tch_appliable_core: ^0.4.3

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

flutter:
