name: tch_common_widgets
description: Flutter common widgets & theming package used by tomaschyly.
version: 0.0.3
# homepage: 
repository: https://github.com/tomaschyly/tch_common_widgets
issue_tracker: https://github.com/tomaschyly/tch_common_widgets/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  tch_appliable_core: ^0.4.3

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tomaschyly.tch_common_widgets
        pluginClass: TchCommonWidgetsPlugin
      ios:
        pluginClass: TchCommonWidgetsPlugin
      linux:
        pluginClass: TchCommonWidgetsPlugin
      macos:
        pluginClass: TchCommonWidgetsPlugin
      windows:
        pluginClass: TchCommonWidgetsPlugin
      web:
        pluginClass: TchCommonWidgetsWeb
        fileName: tch_common_widgets_web.dart
